<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promise</title>
</head>

<body>
    <script>

        const PENDING = 'pending'
        const FULFILLED = 'fulfilled'
        const REJECTED = 'rejected'
        class Promise {
            constructor(excutor) {
                this.status = PENDING

                this.value = undefined
                this.reason = undefined

                this.onfulfilledCallBack = []
                this.onrejectedCallBack = []

                let resolve = (value) => {
                    if (this.status === PENDING) {
                        this.value = value
                        this.status = FULFILLED

                        this.onfulfilledCallBack.forEach(fn => fn())
                    }
                }

                let reject = (reason) => {
                    if (this.status === REJECTED) {
                        this.reason = reason
                        this.status = REJECTED

                        this.onrejectedCallBack.forEach(fn => fn())
                    }
                }

                try {
                    excutor(resolve, reject)
                } catch (e) {
                    reject(e)
                }

            }

            then(onfulfilled, onrejected) {
                if (this.status === FULFILLED) {
                    onfulfilled(this.value)
                }

                if (this.status === REJECTED) {
                    onrejected(this.reason)
                }


                if (this.status === PENDING) {

                    this.onfulfilledCallBack.push(() => {
                        onfulfilled(this.value)
                    })

                    this.onrejectedCallBack.push(() => {
                        onrejected(this.reason)
                    })
                }
            }

            catch(onrejected) {
                return this.then(undefined, onrejected)
            }

            finally(fn) {
                return this.then(value => {
                    return Promise.resolve(fn()).then(()=>value)
                }, reason => {
                    return Promise.resolve(fn()).then(() => {throw reason})
                })
            }

            // 所有的promise执行成功触发成功的回调
            // 成功的promise的参数是所有成功的promise的value的数组
            // 失败就返回第一个失败的promise的reason
            static all(promises) {
                if (!Array.isArray(promises)) {
                    throw new Error('need a array')
                }
                return new Promise((resolve, reject) => {
                    const res = []
                    let num = 0
                    promises.forEach(promise => {
                        promise.then(value => {
                            res.push(value)
                            num++
                            if (num === promises.length) {
                                resolve(res)
                            }
                        }, reason => {
                            reject(reason)
                        })
                    }).catch(e){
                        reject(e)
                    }
                })
            }



            // 所有传入的promise都完成之后成功
            // 适用于彼此不依赖的异步任务完成，得到每一个promise的结果
            static allSettled(iterable) {
                return new Promise((resolve, reject) => {
                    const res = []
                    let count = iterable.length
                    iterable.forEach((p => {
                        p.then((value) => {
                            res.push(value)
                        }, (reason) => {
                            res.push(reason)
                        }).finally(() => {
                            if (!--count)
                                resolve(res)
                        })
                    }))
                })
            }

            // 有一个promise成功，返回成功的promise值
            // 所有的promise都reject，才会reject失败的信息
            static any(iterable) {

                return new Promise((resolve, reject) => {
                    let len = iterable.length
                    const errs = []
                    if (len === 0) reject(errs)
                    iterable.forEach(p => {
                        p.then(value => {
                            resolve(value)
                        }, reason => {
                            len--
                            if (len === 0) {
                                reject(errs)
                            }
                        })
                    })
                })
            }

            // 返回第一个promise执行完的值
            // d第一个返回的可以是成功的promise,也可以是失败的promise
            static race(promises) {
                if (!Array.isArray(promises)) {
                    throw new Error('need a array')
                }

                return new Promise((resolve, reject) => {
                    promises.forEach(p => {
                        Promise.resolve(p).then(value => {
                            resolve(value)
                        }, reason => {
                            reject(reason)
                        })
                    })
                })
            }
        }

        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('14441')
            }, 1000);
        })

        p.then((value) => {
            console.log(value);
        })
    </script>
</body>

</html>